# Generated by Django 5.0.6 on 2024-05-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tasks_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
